<?php $pageTitle='Home'; require_once __DIR__.'/functions.php'; $courses=db()->query("SELECT * FROM courses ORDER BY id DESC LIMIT 6")->fetchAll(); $courseCount=(int)db()->query("SELECT COUNT(*) FROM courses")->fetchColumn(); $noteCount=(int)db()->query("SELECT COUNT(*) FROM resources")->fetchColumn(); $appCount=(int)db()->query("SELECT COUNT(*) FROM applications")->fetchColumn(); include 'includes/header.php';?>
<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">🎓 Learn • Practice • Grow</span><h1>Learn smarter.<br><span class="gradient">Grow faster.</span></h1><p>Practical computer education, coding courses, tutorials, notes and useful downloads — designed for students and beginners.</p><div class="btns"><a class="primary" href="courses.php">Explore Courses</a><a class="secondary" href="tutorials.php">Read Tutorials</a></div></div><div class="hero-card"><div class="code">&lt;learn&gt;
  Start with basics.
  Practice every day.
  Build real projects.
  Keep growing.
&lt;/learn&gt;</div></div></div></section>
<section class="section"><div class="container"><div class="stats"><div class="stat"><strong><?=$courseCount?></strong><span>Courses</span></div><div class="stat"><strong><?=$noteCount?></strong><span>Study resources</span></div><div class="stat"><strong><?=$appCount?></strong><span>Applications</span></div><div class="stat"><strong>24/7</strong><span>Learning access</span></div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><h2>Featured Courses</h2><p class="muted">Structured, beginner-friendly learning.</p></div><a class="secondary" href="courses.php">View all</a></div><div class="cards"><?php foreach($courses as $c):?><article class="card"><div class="thumb"><?=e($c['icon'])?></div><div class="card-body"><h3><?=e($c['title'])?></h3><p><?=e($c['description'])?></p><div class="meta"><span><?=e($c['level'])?></span><span>⏱ <?=e($c['duration'])?></span><span>📚 <?=e($c['lessons'])?> lessons</span></div><div class="price"><?=e($c['price'])?></div><a class="primary" style="margin-top:14px" href="course.php?slug=<?=urlencode($c['slug'])?>">View Course</a></div></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><div class="feature-grid"><div class="feature"><div class="ico">💻</div><h3>Computer Fundamentals</h3><p class="muted">Start from zero and understand computers clearly.</p></div><div class="feature"><div class="ico">🌐</div><h3>Web Development</h3><p class="muted">HTML, CSS, JavaScript, PHP and databases.</p></div><div class="feature"><div class="ico">📱</div><h3>Applications</h3><p class="muted">Useful software and student tools in one download center.</p></div></div></div></section>
<?php include 'includes/footer.php';?>
