<?php
require_once __DIR__.'/functions.php';
if(isset($_GET['logout'])){unset($_SESSION['student_id'],$_SESSION['student_name']);redirect('student-login.php');}
if(student_logged()){$pageTitle='Student Dashboard';$st=db()->prepare("SELECT * FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.student_id=? ORDER BY e.id DESC");$st->execute([$_SESSION['student_id']]);$enrolled=$st->fetchAll();include 'includes/header.php';?>
<section class="page-head"><div class="container"><h1>Student Dashboard</h1><p class="muted">Welcome, <?=e($_SESSION['student_name'])?>.</p><a class="secondary" href="student-login.php?logout=1">Logout</a></div></section><section class="section" style="padding-top:10px"><div class="container"><div class="panel"><h2>My Courses</h2><?php if(!$enrolled):?><p class="muted">You have not enrolled in a course yet. Browse Courses to start.</p><?php else:?><div class="list"><?php foreach($enrolled as $c):?><div class="resource"><div><h3><?=e($c['title'])?></h3><p class="muted"><?=e($c['level'])?> · <?=e($c['duration'])?></p></div><a class="primary" href="course.php?slug=<?=urlencode($c['slug'])?>">Open</a></div><?php endforeach;?></div><?php endif;?></div></div></section><?php include 'includes/footer.php';exit;}
$pageTitle='Student Login';$error='';$mode=$_GET['mode']??'login';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{if(($_POST['action']??'')==='register'){$name=trim($_POST['name']);$email=strtolower(trim($_POST['email']));$pass=$_POST['password'];if(strlen($pass)<6)throw new RuntimeException('Password must be at least 6 characters.');$st=db()->prepare("INSERT INTO students(name,email,password_hash) VALUES(?,?,?)");$st->execute([$name,$email,password_hash($pass,PASSWORD_DEFAULT)]);$id=db()->lastInsertId();$_SESSION['student_id']=$id;$_SESSION['student_name']=$name;redirect('student-login.php');}else{$st=db()->prepare("SELECT * FROM students WHERE email=?");$st->execute([strtolower(trim($_POST['email']))]);$s=$st->fetch();if(!$s||!password_verify($_POST['password'],$s['password_hash']))throw new RuntimeException('Invalid email or password.');$_SESSION['student_id']=$s['id'];$_SESSION['student_name']=$s['name'];$redirect=$_POST['redirect']??'';redirect($redirect&&preg_match('/^[a-zA-Z0-9_.-]+\.php/', $redirect)?$redirect:'student-login.php');}}catch(Throwable $e){$error=$e->getMessage();}}
include 'includes/header.php';?>
<section class="section"><form class="form-box panel" method="post"><h1><?=$mode==='register'?'Create Account':'Welcome!'?></h1><p class="muted"><?=$mode==='register'?'Create your student account.':'Login to your student account.'?></p><?php if($error):?><div class="notice"><?=e($error)?></div><?php endif;?><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="<?=$mode==='register'?'register':'login'?>"><input type="hidden" name="redirect" value="<?=e($_GET['redirect']??'')?>"><?php if($mode==='register'):?><label>Name</label><input name="name" required><?php endif;?><label>Email</label><input required type="email" name="email"><label>Password</label><input required type="password" name="password" minlength="6"><button class="primary" style="width:100%"><?=$mode==='register'?'Create Account':'Login'?></button><p class="muted"><?php if($mode==='register'):?>Already have an account? <a href="student-login.php">Login</a><?php else:?>New student? <a href="student-login.php?mode=register">Create account</a><?php endif;?></p></form></section><?php include 'includes/footer.php';?>
